shivprime94/Data-Structure-Algorithms

MergeSort.cpp
=> Merge sort 

reversewordwise.cpp
Reverse the given string word wise. That is, the last word in given string should come at 1st place, last second word at 2nd place and so on. Individual words should remain as it is.
=> Reverse word wise

doraeomon.py, factorial.py, gcd_lcm.py, guesser.py, lucky_four.py
Hey There,
Learn how to draw a Doraemon using a python turtle.
=> Doraemon Using Python

Rat in a Maze.cpp
An application of backtracking
=> Rat in a Maze problem

codechef problems/longestANDsubarray.cpp
added codechef longest AND subarray problem solution in c++
=> added longestANDsubarray problem

Algorithms CPP/BinaryTree_VerticalSum.cpp
Code for printing Vertical Sum of Binary Tree in c++.
=> Created BinaryTree_VerticalSum.cpp

Algorithms CPP/BinaryTree_AllNodesSum.cpp
Sum of all nodes in a Binary Tree
=> Created BinaryTree_AllNodesSum.cpp

Algorithms CPP/BinaryTree_ReverseLevelOrder.cpp
Print reverse level order traversal using stack and queue
=> Created BinaryTree_ReverseLevelOrder.cpp

Algorithms CPP/BinaryTree_SpiralLevelOrderTraversal.cpp
Level order traversal in spiral form of a Binary Tree
=> Created BinaryTree_SpiralLevelOrderTraversal.cpp

Algorithms CPP/Inorder_without_recursion_BT.cpp
Inorder traversal of Binary Tree without recursion and using Stack.
=> Created Inorder_without_recursion_BT.cpp

Algorithms CPP/Inorder_successor_BT.cpp
Inorder Successor for a  binary tree.
=> Created Inorder_successor_BT.cpp

Algorithms CPP/BinaryTree_LevelOrderTraversal.cpp
Level Order traversal of binary tree using queue
=> Created BinaryTree_LevelOrderTraversal.cpp

Algorithms CPP/nthNode_Inorder_BT.cpp
Print nth Node in Inorder traversal of a Binary tree
=> Created nthNode_Inorder_BT.cpp

Codeforces Problems/116A.cpp, Codeforces Problems/118A.cpp, Codeforces Problems/122A.cpp
added solution of codeforces problem . can you please check and merge it
=> added codeforces solution

diagonal diff.cpp
please accept my pull request for hactober fest 2021.
=> diagonal difference

python/face_analyzer_deepface.py
Good evening, I made a cool script using deepface library in python to analyze the face data of the person via image file or it can be taken 1 step further to add live camera emotions and facial expressions but I am not able to perform is successfully due to hardware limitation but would be cool to implement.
=> Adding face_analyzer_deepface.py

sort_bubble.dart
a program for sorting uisng bubble sort algorithm in dart
=> bubble sorting in dart

codechef problems/reverseint.js
Add new solution for reverseint problem please review @Viz38
=> add reverse int problem in js

Leetcode Problems/SlidingWindowMaximum.cpp
Hi @shivprime94 
I have added the CPP solution to the leetcode problem "Sliding Window Maximum"
Kindly review and merge the PR :)
=> added Sliding Window maximum from leetcode

leetcode hard/NQueens.cpp, leetcodeproblems/medium/SetMatrixZero.cpp
NQueens Problem Statement:
The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.
Given an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.
Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.
SetMatrixZero Problem Statement:
Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's, and return the matrix.
You must do it in place.
=> Add Leetcode problem solutions in cpp

.vscode/settings.json, Leetcode Problems/3SUM.cpp, Leetcode Problems/3sum_Closest.cpp
Problem statement - Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.
Notice that the solution set must not contain duplicate triplets.
Example 1:
Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
Example 2:
I have added its cpp optimised solution
=> added 3SUM problem

Algorithms CPP/Stack/Applications/Evaluation-Prefix-Postfix(stack).cpp, Algorithms CPP/Stack/Applications/Reverse_Function(linklist).cpp, Algorithms CPP/Stack/Applications/Reverse_Function(stack).cpp, Algorithms CPP/Stack/Applications/balacing paraenthesis(stack).cpp, Algorithms CPP/Stack/Stack( with linked-list).cpp, Algorithms CPP/Stack/Stack(with array).cpp
all stack implementation of dsa concepts
=> stack implementation(DSA concepts)

MoveZeros.cpp, NextPermutation.cpp
question: Implement next permutation, which rearranges numbers into the lexicographically next greater permutation of numbers.
If such an arrangement is not possible, it must rearrange it as the lowest possible order (i.e., sorted in ascending order).
The replacement must be in place and use only constant extra memory.
=> NextPermutation

leetcode hard/EditDistance.cpp, leetcodeproblems-easy/InvertedBinaryTree.cpp
Problem Statement:
Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.
You have the following three operations permitted on a word:
Insert a character
Delete a character
Replace a character
=> add EditDistance solution in cpp

Algorithms CPP/Dutch_National_Flag_sort.cpp
I have explained the optimized way to sort the array containing 0's, 1's, and 2's using *DNF Sort (Dutch National Flag Sort)*.
- Useful Comments
- Beginner Friendly Code Style
=> DNF (Dutch National Flag) Sort in Cpp

Leetcode Problems/TwoSumHashMap.java
- Added TwoSum implementation using HashMap
- Time Complexity is O(n)
=> TwoSum HashMap O(n) implementation java

Algorithms CPP/Scrambled_String.cpp
In this, I have the problem named **Scrambled String** how we have to approach the question and solve it by using recursion.
-  Easy to understand comments
-  Clean code
=> Scarmbled String in cpp

readme.md
Added a readme file please have a look and merge my pull request.
=> Added readme file to your repository. #265

leetcodeproblems-easy/ContainsDuplicate.java, leetcodeproblems-easy/RomanToInteger.java
=> added Contains Duplicate Solution

leetcodeproblems-easy/HappyNumber.java
Solution added for : 
https://github.com/shivprime94/Data-Structure-Algorithms/issues/277
=> Happy Number solution added

GFG/stockBuySell.cpp, Leet Code/stockyBuySell.cpp
Stock buy & Sell Leet Code & GFG Practice Q's
=> GFG & Leet Code stock buy sell

leetcodeproblems-easy/LongestCommonPrefix.java
Added solution for : 
https://github.com/shivprime94/Data-Structure-Algorithms/issues/276
=> Longest Common Prefix solution added

CSES Problem Set/Graph/Knight's Tour.cpp
Added Knight's Tour.cpp in CSES folder under Graphs section.
=> Added Knight's Tour Problem

Algorithms CPP/Tower Of Hanoi.cpp
=> Tower of Hannoi

leetcodeproblems-easy/BuySellStock.java
Solution for :
https://github.com/shivprime94/Data-Structure-Algorithms/issues/279
=> addded solution for Buy Sell Stock

Leetcode Problems/Find the Duplicate Number
Find the Duplicate Number
Medium level
Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive.
There is only one repeated number in nums, return this repeated number.
You must solve the problem without modifying the array nums and uses only constant extra space.
link : https://leetcode.com/problems/find-the-duplicate-number/
=> Adding Find the Duplicate Number

Algorithms CPP/Linked List/Singly Linked List/detectCycle.cpp
Program to detect a Cycle in a Linked List
=> Added Program to detect cycle in Linked List

Algorithms in Operating Systems/CPU Scheduling Algorithms/FCFS Algorithm.c, Algorithms in Operating Systems/Memory Allocation Algorithms/Best Free Algorithm.c
I am requesting you to merge my PR, which contains all the necessary algorithms used in CPU scheduling and Memory Allocation required in the Operating Systems.
=> Added Operating System Algorithms

Algorithms CPP/Strings/autoPasswordGenerator.cpp
Automatic Password Generator using CPP
=> Added Code under String to automatically generate a password

Leetcode Problems/Non-overlapping Intervals.cpp
Added the C++ code for LeetCode Q.435.
=> Non-overlapping Intervals.cpp

Leetcode Problems/Longest Repeating Character Replacement.cpp
Added the C++ code for LeetCode Q.424.
=> Longest Repeating Character Replacement.cpp

Algorithms CPP/Quick_Sort_using_Recursion.cpp
I have written code for Quick Sort using Recursion.
=> Quick_Sort_using_Recursion.cpp

Algorithms CPP/Insertion Sort using Recursion.cpp
I have written code for Insertion Sort using Recursion.
=> Insertion Sort using Recursion.cpp

Algorithms CPP/Selection Sort using Recursion.cpp
I have written code for Selection Sort using Recursion.
=> Selection Sort using Recursion.cpp

First Missing Positive
First Missing Positive in python
=> First Missing Positive

Algorithms CPP/Bubble Sort using Recursion.cpp
I have written code for Bubble Sort using Recursion.
=> Bubble Sort using Recursion.cpp

CSES Problem Set/Graph/Download Speed.cpp
Added Download Speed.cpp file under CSES Problem Set under Graphs Section.
=> Added Download Speed problem in CSES

Divide array into equal pairs
Time complexity: O(N)
Space complexity: O(1)
=> Divide array into equal pairs program in C++

CSES Problem Set/Graph/download.cpp
=> CSES - Download Speed 

Leetcode Easy/Divide_Array_Into_Equal_Pairs.java
I would like to add a Java code for this problem.
Time Complexity: O(N)
Space Complexity: O(N)
Problem Link: [https://leetcode.com/problems/divide-array-into-equal-pairs/](https://github.com/shivprime94/Data-Structure-Algorithms/issues/url)
Issue Number : #315
=> added Divide Array into Equal Pairs in Java

Trapping rainwater problem
=> Trapping Rainwater Problem in C++

Divide Array into Equal Pairs
Divide Array into Equal Pairs using python
=> Divide Array into Equal Pairs

Jump Game
=> Jump Game Leetcode medium

Odd Even Linkedlist
=> Odd Even Linkedlist

Codeforces Problems/1721A.py
=> Added solution for 1721A- IMAGE problem

Leetcode Problems/Optimal Partition of String.cpp
I have added code of medium level in leetcode.(2405. Optimal Partition of String).
=> Create Optimal Partition of String.cpp

Leetcode Problems/Strictly Palindromic Number.cpp
I have added code of medium level in leetcode.(2396. Strictly Palindromic Number).
=> Create Strictly Palindromic Number.cpp

Leetcode Problems/Partitioning Into Minimum Number Of Deci-Binary Numbers.cpp
I have added code of medium level in leetcode.(1689. Partitioning Into Minimum Number Of Deci-Binary Numbers).
=> Create Partitioning Into Minimum Number Of Deci-Binary Numbers.cpp

Leetcode Problems/Divide Intervals Into Minimum Number of Groups.cpp
I have added code of medium level in leetcode.(2406. Divide Intervals Into Minimum Number of Groups).
=> Create Divide Intervals Into Minimum Number of Groups.cpp

codechef problems/WATESTCASES.cpp
WA Test Cases (WATESTCASES) under codechef problems 
- Language : Cpp
- Time Complexity : $O( n log n )$
- Space Complexity: $O( n )$
Hi @shivprime94, please review and merge my PR
=> added WATESTCASES.cpp

codechef problems/EQLZING.cpp
Equalize Numbers (EQLZING) under codechef problems 
- Language : Cpp
- Time Complexity : $O( 1 )$
- Space Complexity: $O( 1 )$
Hi @shivprime94, please review and merge my PR
=> added EQLZING.cpp

Algorithms CPP/Stack/nextgreatestelement.cpp, Algorithms CPP/Stack/stackusingll.cpp
added a solution of next greatest element.
=> added a stack implementation.

Queue using Stacks.cpp
@shivprime94 Accept my PR under Hacktoberfest
=> Queue using Stacks

Algorithms CPP/gcd_recursive.cpp
=> Added Recursive C++ code for gcd (Euclid's Algo).

Leetcode Easy/Palindrome Linked List.cpp
@shivprime94 Accept my PR under Hacktoberfest
=> Palindrome Linked List

Leetcode Problems/dungeon_game.cpp, Leetcode Problems/house_robber.cpp, Leetcode Problems/house_robber_2.cpp, Leetcode Problems/house_robber_3.cpp, Leetcode Problems/longest_common_subsequence.cpp, Leetcode Problems/longest_increasing_subsequence.cpp
These are some famous questions of dynamic programming which everyone must have a look........
=> Added dynamic programming problems

doublycircular.cpp, doublylinkedlist.cpp, singlycircularlinkedlist.cpp, singlylinkedlist.cpp
basic codes for all types of linked lists
=> basic codes for all types of linked lists

Algorithms CPP/slidingWindow.cpp
This is Sliding window approach in CPP .
Please add Hacktoberfestaccepted2022 label before Merging.
Thankyou for your support.
=> Sliding Window Approach

CSES Problem Set/Graph/Mail Delivery.cpp
Added Mail Delivery.cpp file in Graphs Section of CSES Problem Set
=> Added Mail Delivery Problem of CSES

codechef problems/April Long One 2022(APRIL221D )/Dazzling_AXNODR_Challenge.cpp
https://www.codechef.com/viewsolution/62477679
=> Dazzling AXNODR Challenge.cpp (April Long One 2022)

Swift/Linked-List/SingleLinkedList.swift
I have added Single Linked List Data Structure with Simple Program Implementation in Swift
=> Add Single Linked List Data Structure in Swift

README.md
created readme file and describe about the repository. I think you also need and license for this repository
=> created Readme.md

ReverseLinkedList.cpp, primeprint2.cpp
I have written a linked list and prime number code in c++.
=> AddedCPPprogram

Leetcode Problems/Rotate matrix by 90 degree
Link to the problem statement:- https://leetcode.com/problems/rotate-image/
=> Create Rotate matrix by 90 degree

Swift/Queue/Queue.swift
I have added Queue Data Structure with Simple Program Implementation in Swift
=> Add Queue Data Structure in Swift

Swift/Stack/Stack.swift
I have added Stack Data Structure with Simple Program Implementation in Swift
=> Add Stack Data Structure in Swift

Swift/Linked-List/DoubleLinkedList.swift
I have added Double Linked List Data Structure with Simple Program Implementation in Swift
=> Add Double Linked List Data Structure in Swift

Codeforces Problems/EVMHACK@codechef.cpp
This is a cpp code regarding EVMHACK problem
=> EVMHACK.CPP

Go/Data-Structures/Hash-Table/main.go
I have added Hash Table Data Structure with Simple Simulation in Go
=> Add Hash Table Data Structure in Go

Go/Data-Structures/Single-Linked-List/main.go
I have added Single Linked List Data Structure with Simple Simulation in Go
=> Add Single Linked List Data Structure in Go

Go/Data-Structures/Binary-Search-Tree/main.go
I have added Binary Search Tree Data Structure with Simple Simulation in Go
=> Add Binary Search Tree Data Structure in Go

mergesort.cpp
plz merge it for the hacktober fest 2022
=> Created mergesort.cpp

GFG/coinchange.cpp
The question is you have been given coins of different values in the form of array elements also you are given a sum(target value) which you have to generate using given coins. Task is to find the number of ways in which that sum could be formed using given coins.
=> Coin change problem Geeks for Geeks

GFG/FlatteningLL.cpp
Given a Linked List of size N, where every node represents a sub-linked-list and contains two pointers:
(i) a next pointer to the next node,
(ii) a bottom pointer to a linked list where this node is head.
Each of the sub-linked-list is in sorted order.
Flatten the Link List such that all the nodes appear in a single level while maintaining the sorted order.
=> Flattening a Linked List

Algorithms CPP/2D arrays/Smallest positive missing.cpp
I have written a code for Smallest positive missing.
=> Create  Smallest positive missing.cpp

Algorithms CPP/2D arrays/Minimum Platform.cpp
I have written a code for Minimum platform.
=> Create Minimum Platform.cpp

Codeforces Problems/719E-Arranging The Sheep.py, Leetcode Problems/medium/12 Integer to Roman.py, Leetcode Problems/medium/692 Top K Frequent Words.py
Few leetcode Medium added which are not present in folder
=> Leetcode Medium Problem added

Algorithms CPP/2D arrays/Majority Element.cpp
I have written a code for Majority Element.
=> Create Majority Element.cpp

Algorithms CPP/2D arrays/Array waveform.cpp
I have written a code for Array waveform.
=> Create Array waveform.cpp

Algorithms CPP/2D arrays/Trappinf rainwater.cpp
I have written a code for trapping rainwater problem
=> Create Trappinf rainwater.cpp

Algorithms CPP/RedBlackTree.cpp, Algorithms CPP/TowerOfHanoi.cpp
=> RedBlackTree and ToerOfHanoi

Leetcode Problems/medium/76.Minimum Window Substring.py, Leetcode Problems/medium/8.String to Integer (atoi).py, Leetcode Problems/medium/Jump Game II.py
=> Leetcode Daily + Leetcode Medium Problems added

Leetcode Easy/RemoveElement.cpp
Added Remove Element in Leetcode Easy
=> Added Remove Element in Leetcode Easy

python/min_path_sum.py
Added Minimum Path sum in Python. My Open Source Contribution towards Hacktoberfest.
=> Added Python Code for Minimum path sum in a Matrix. DP solution with memoization, Tabulation & Space Optimize

Algorithms in C#/Dijkstra-Algorithm.cs, Algorithms in C#/Floyd-Warshall-Algorithm.cs
Floyd–Warshall Algorithm for determining the shortest paths in a weighted graph with positive or negative edge weights
=>  Floyd–Warshall Algorithm

GFG/Max_Circular_Subarray_Sum.cpp
Given an array arr[] of N integers arranged in a circular fashion. Your task is to find the maximum contiguous subarray sum.
Time Complexity: O(N)
Topic: Arrays.
Solves -  Issue - #468
=> Max Circular Subarray Sum

GFG/Kadanes_Algorithm.cpp
Given an array Arr[] of N integers. Find the contiguous sub-array(containing at least one number) which has the maximum sum and return its sum.
Time Complexity: O(N)
Topic: Array
=> Kadanes_Algorithm

Leetcode Problems/Multiply_Strings.py
Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.
Topic: Strings
=> Multiply Strings

CSES Problem Set/Searching and Sorting/Playlist.cpp, CSES Problem Set/Searching and Sorting/Towers.cpp, Codeforces Problems/1420C1 Pokemon Army(easy).cpp, Codeforces Problems/1420C2 - Pokemon Army(hard).cpp, Codeforces Problems/1708C - Doremy's IQ.cpp, Codeforces Problems/1709C - Recover an RBS.cpp, Codeforces Problems/1721C - MinMax Array Transformation.cpp
Hey, I have added algorithms for certain Codeforces and CSES problems in C++ language.
Please, feel free to recommend any changes.
Thanks & Regards.
=> Added Some Algorithms for Certain Problems

Leetcode Problems/39.Combination_sum.cpp, Leetcode Problems/75. Sort_color.cpp, Leetcode Problems/91. Decode_ways.cpp
leetcode combination sum problem
=> leetcode problem

Leetcode Easy/SingleNumber.java
=> added single-number code

Leetcode Easy/Middle of the Linked List.cpp
Code for finding Middle Element of Linked List
=> Create Middle of the Linked List.cpp

Algorithms CPP/Strings/Finding_Duplicates_In_A_String.c
Duplicated alphabets are displayed with the number of times they occur. This program will only work for lower case alphabets.
=> Finding_Duplicates_In_A_String.c

CSES Problem Set/Subordinates.cpp, CSES Problem Set/Subtree Queries.cpp
Added solutions for Subordinates problem and Subtree queries problem.
Links to the problems are mentioned in the files
Happy Hacktoberfest !
=> Added CSES solutions
